swagger: '2.0'
info:
  title: MusicBee Remote API
  description: MusicBeeRemote
  version: "1.0.0"
host: vmwin:8188
schemes:
  - http
basePath: /
produces:
  - application/json
paths:
  /track:
    get:
      summary: The currently playing track info
      description: |
        The endpoint returns information about the now playing track
      tags:
        - Track
      responses:
        200:
          description: The information of a track
          schema:
            $ref: '#/definitions/TrackInfoResponse'
  /track/cover:
    get:
      summary: The cover of the playing track
      description: |
        The endpoint returns the cover of the currently playing track
      produces:
        - image/jpeg
      tags:
        - Track
      responses:
        200:
          description: The cover image
  /library/albums:
    get:
      parameters:
        - name: limit
          in: query
          description: The max number of elements in the page
          type: integer
        - name: offset
          in: query
          description: The position of the first element in the page
          type: integer
        - name: after
          in: query
          description: The unix epoch after which all the added/mofidied/deleted elements should be returned
          type: integer
      summary: Retrieves the cached albums from the plugin
      description: |
        The endpoints returns album tracks paginated
      tags:
        - Library
        - Albums
      responses:
        200:
          description: A successful response
          schema:
            $ref: '#/definitions/PageResponse'
        500:
          description: Server Error

definitions:
  PageResponse: 
    type: object
    properties:
      data: 
        type: array
        description: An array of data objects that are included in the page returned
      limit: 
        type: integer
        description: The max number of elements contained in the page (depends on the dataset)
      offset:
        type: integer
        description: The position of the first element contained in the page
      total:
        type: integer
        description: The total number of elements available on the server
      code:
        type: integer
        minimum: 100
        maximum: 600
        description: A response code from the plugin API, it should be 200 for success
  Album:
    type: object
    properties:
      id:
        type: integer
        description: The id of the album in the database (primary key)
      name: 
        type: string
        description: The title of the album
      artist_id:
        type: integer
        description: The id of the album artist in the database (foreign key)
      cover_id:
        type: integer
        description: the id of the album cover in the database (foreign key)
      date_added:
        type: long
        description: The exact time that the entry was added to the database unix epoch (seconds)
      date_deleted:
        type: integer
        description: The date (unix epoch in seconds) that the entry was deleted
      date_updated:
        type: integer
        description: The date (unix epoch in seconds) that the entry was updated
  TrackInfoResponse:
    type: object
    properties:
      code:
        type: integer
        minimum: 100
        maximum: 600
        description: A response code from the plugin API, it should be 200 for success
      album:
        type: string
        description: The album of the playing track
      artist:
        type: string
        description: The artist of the playing track
      title:
        type: string
        description: The title of the playing track
      year:
        type: string
        description: The year in which the playing track was released
      path:
        type: string
        description: The path of the file in the filesystem
